### ISSUE TITLE
v4.3.0 workersClient.kv.namespaces.bulkUpdate not a function

### ISSUE THREAD

**Issue by dnalborczyk** [cloudflare/cloudflare-typescript#2642]
### Confirm this is a Typescript library issue and not an underlying Cloudflare API issue

- [x] This is an issue with the Typescript library

### Describe the bug

The `bulkUpdate` function on `workersClient.kv.namespaces` appears to have been removed.

Looks like a runtime js error as well as a typescript type error.

works with v4.2.0

### Code snippets

```Typescript
import Cloudflare from "cloudflare"

const workersClient = new Cloudflare(...)

await workersClient.kv.namespaces.bulkUpdate(...)
// throws TypeError: workersClient.kv.namespaces.bulkUpdate is not a function
```

### OS

macOS

### Runtime version

Typescript v5.8.3

### Library version

v4.3.0

**Comment by Razzmatazzz** [comment]
This appears to have been moved to `client.kv.namespaces.keys.bulkUpdate`. A minor version release should not include breaking changes like this, especially without any kind of explicit warning.

**Comment by Cherry** [comment]
cc @jhutchings1 not sure what might have happened here for a breaking change to get introduced in v4.

**Comment by rattrayalex** [comment]
Thanks James – I agree. Will bump this internally, I hope we're able to get something out tomorrow.

**Comment by Cherry** [comment]
It seems this actually may have been resolved in v4.4.0 at https://github.com/cloudflare/cloudflare-typescript/commit/d9218c88c04916fadf473d618a272b6e39042e3d a couple of weeks ago, but just missed in the noise of the unreadable changelog. Thanks for the fix.

**Comment by rattrayalex** [comment]
Yes, sorry for the changelog – we are trying to find a way to improve the commit messages, including to say things like `fixes #2642`, but with the scale/volume of changes it is a challenge. 

Apologies for not updating this thread as well.

**Comment by mgirouard** [comment]
Closing since this looks resolved. Please reopen if this was a mistake!
